version: '3.7'

services:
  server:
    container_name: server
    build: ./services/server
    volumes:
    - $PWD:/var/www/localhost/htdocs
    - $PWD/services/server/etc/php/7.2/php.ini:/etc/php/7.2/php.ini
    ports:
    - "80:80"
    links:
    - "mariadb"

  mariadb:
    container_name: mariadb
    image: bianjp/mariadb-alpine
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
    - $PWD/services/mariadb/data:/var/lib/mysql
    ports:
    - "3306:3306"