version: '3.7'

services:
  apache:
    container_name: apache
    build: ./services/server-alpine-apache-php7.3
    volumes:
    - $PWD:/var/www/localhost/htdocs
    - $PWD/services/server-alpine-apache-php7.3/etc/php/7.3/php.ini:/etc/php/7.3/php.ini
    - $PWD/services/server-alpine-apache-php7.3/etc/apache2/httpd.conf:/etc/apache2/httpd.conf
    ports:
    - "127.0.0.1:80:80"
    links:
    - "mariadb"

  mariadb:
    container_name: mariadb
    image: bianjp/mariadb-alpine:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
    - $PWD/services/db-alpine-mariadb/data:/var/lib/mysql
    ports:
    - "127.0.0.1:3306:3306"