version: '3.7'

services:
  server:
    container_name: server
    build: ./services/server-alpine-apache-php7.3
    volumes:
    - $PWD:/var/www/localhost/htdocs
    - $PWD/services/server-alpine-apache-php7.3/etc/php/7.3/php.ini:/etc/php/7.3/php.ini
    ports:
    - "80:80"
    links:
    - "db"

  db:
    container_name: db
    image: bianjp/mariadb-alpine:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
    - $PWD/services/db-alpine-mariadb/data:/var/lib/mysql
    ports:
    - "3306:3306"